config/routes.rb
Rails.application.routes.draw do
  root 'tables#index'
  devise_for :users

  resources :characters, only: [:index, :new, :create, :edit, :update]
  resources :tables, only: [:index, :show, :new, :create, :update] do
    resources :combat_trackers, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :table, optional: true
  has_many :zones, through: :combatants
end

app/models/combat_tracker.rb
class CombatTracker < ApplicationRecord
  belongs_to :table
  has_many :zones

  def move(character:, zone:)
    zone.move(character: character)
  end
end

app/models/combatant.rb
class Combatant < ApplicationRecord
  belongs_to :character
  belongs_to :zone
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :user
  has_many :combat_trackers
  belongs_to :active_combat, optional: true, class_name: "CombatTracker"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :characters
  has_many :tables
 end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :combat_tracker
  has_many :combatants
  has_many :characters, through: :combatants

  def move(character:)
    combatant = Combatant.find_or_initialize_by(character: character)
    combatant.zone = self
    combatant.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:edit, :update]

  def index
    @characters = current_user.characters
  end

  def new
    @character = Character.new
  end

  def create
    character = current_user.characters.build(character_params)

    if character.save!
      flash[:notice] = "#{character.name} created!"
      redirect_to characters_path
    else
      flash[:alert] = 'Unable to create character'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @character.update(character_params)
      flash[:notice] = "#{@character.name} updated!"
      redirect_to characters_path
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :sheet_url, :table_id)
  end

  def set_character
    @character = Character.find(params[:id])
  end
end

app/controllers/combat_trackers_controller.rb
class CombatTrackersController < ApplicationController
  def new
    @combat_tracker = CombatTracker.new
  end

  def create
    table = Table.find(params[:table_id])
    combat_tracker = table.combat_trackers.build(combat_tracker_params)

    if combat_tracker.save!
      flash[:notice] = "#{combat_tracker.name} created!"
      redirect_to table
    else
      flash[:alert] = 'Unable to create combat tracker'
      render 'new'
    end
  end

  private

  def combat_tracker_params
    params.require(:combat_tracker).permit(:name)
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :update]

  def index
    @tables = current_user.tables
    @characters = current_user.characters
  end

  def new
    @table = Table.new
  end

  def create
    table = current_user.tables.build(table_params)
    table.slug = table.name.parameterize

    if table.save!
      flash[:notice] = "#{table.name} created!"
      redirect_to tables_path
    else
      flash[:alert] = 'Unable to create table'
      render 'new'
    end
  end

  def show
    @character = Character.find_by(table: @table)
    render layout: false
  end

  def update
    if @table.update(table_params)
      flash[:notice] = "#{@table.name} updated!"
      redirect_to @table
    end
  end

  private

  def table_params
    params.require(:table).permit(:name, :description, :active_combat_id)
  end

  def set_table
    @table = Table.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: @character) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :sheet_url %>
  <%= f.text_field :sheet_url %>

  <% unless Table.all.empty? %>
    <%= f.label :table %>
    <%= f.collection_select :table_id, Table.all, :id, :name %>
  <% end %>
  <%= f.submit yield(:button_text) %>
<% end %>

app/views/characters/edit.html.erb
<% provide(:button_text, 'Update character') %>
<h3>Edit <%= @character.name %></h3>
<%= render 'form' %>

app/views/characters/index.html.erb
<h1>My characters</h1>

<%= link_to 'Add a character', new_character_path %>

<% if @characters %>
  <% @characters.each do |character| %>
    <div id="<%= character.id %>">
      <h3><%= character.name %></h3>
      <%= link_to "Edit #{character.name}",
                    edit_character_path(character),
                    id: "edit-#{character.id}" %>
    </div>
  <% end %>
<% else %>
  <p>You haven’t created any characters yet. Why not add one now?</p>
<% end %>

app/views/characters/new.html.erb
<% provide(:button_text, 'Add character') %>
<h3>Add a character</h3>
<%= render 'form' %>

app/views/combat_trackers/_form.html.erb
<%= form_with(model: @combat_tracker, url: table_combat_trackers_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/combat_trackers/new.html.erb
<% provide(:button_text, 'Add combat tracker') %>
<h3>Add a combat tracker</h3>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabletopCompanion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_user_session_path, data: { "turbo-method": :delete } %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end  %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tables/_combat_tracker.erb
<% if current_user == @table.user %>
  <%= link_to 'New combat', new_table_combat_tracker_path(table_id: @table.id) %>
<% end %>

<h5>Active combat</h5>
<%= form_with(model: @table) do |f| %>
  <%= f.label :active_combat %>
  <%= f.collection_select :active_combat_id, @table.combat_trackers, :id, :name %>

  <%= f.submit 'Set as active combat' %>
<% end %>

<% if @table.active_combat %>
  <%= @table.active_combat.name %>
<% else %>
  <p>No combat in progress. Select a combat above or <%= link_to 'make a new one', new_table_combat_tracker_path(table_id: @table.id) %>.</p>
<% end %>

app/views/tables/_form.html.erb
<%= form_with(model: @table) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/tables/_table.html.erb
<%= link_to table.name, table, id: "table-#{table.id}" %>

app/views/tables/index.html.erb
<h1>Welcome</h1>

<%= link_to 'My characters', characters_path %>

<h2>My tables</h2>
<%= link_to 'New table', new_table_path %>

<h4>Running:</h4>
<% current_user.tables.each do |table| %>
  <%= render table %>
<% end %>

<h4>Playing</h4>
<% current_user.characters.each do |character| %>
  <%= render character.table if character.table %>
<% end %>

app/views/tables/new.html.erb
<% provide(:button_text, 'Add table') %>
<h3>Add a table</h3>
<%= render 'form' %>

app/views/tables/show.html.erb
<!doctype html>
<html>
<head>
  <title><%= @table.name %></title>
  <%= stylesheet_link_tag "table" %>
</head>
<body>
  <div id="viewport">
    <div id="panel-one">
      <% if @character.nil? %>
        <p>No active character, select one below or <%= link_to 'make a new one', new_character_path %>.</p>
      <% elsif @character.sheet_url.blank? %>
        <p>Please <%= link_to 'set your character sheet', edit_character_path(@character) %>.</p>
      <% else %>
        <iframe src="<%= @character.sheet_url %>"></iframe>
      <% end %>
    </div>
    <div id="panel-two">
      <%= render partial="combat_tracker" %>
    </div>
    <div id="spacer"></div>
  </div>
  <nav id="menu-bar">
    <ul>
      <li><a href="#panel-one">Sheet</a></li>
      <li><a href="#panel-two">Combat</a></li>
    </ul>
  </nav>
</body>
</html>